DROP TABLE GRUPO;
DROP TABLE CANCION;

CREATE TABLE GRUPO(
    id_grupo INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    nombreGrupo VARCHAR(200) NOT NULL,
    imagenGrupo VARCHAR(200) NOT NULL,
    PRIMARY KEY (id_grupo)
);

CREATE TABLE CANCION(
    id_cancion INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    id_grupo INT NOT NULL,
    nombreCancion VARCHAR(200) NOT NULL,
    PRIMARY KEY (id_cancion)
);

 -- /////////////////////////////////////////////////

SELECT * FROM GRUPO G 
INNER JOIN CANCION C
ON C.id_grupo = G.id_Grupo;

--EJEMPLO INSERT GRUPO

INSERT INTO GRUPO(nombreGrupo,imagenGrupo) VALUES('asdf','ADASDF');

--EJEMPLO INSERT CANCION

INSERT INTO CANCION(id_grupo,nombreCancion) VALUES(0,'ADASDF2');
